INSERT INTO IMG_COLABORADOR(
    FILENAME,
    CONTENT,
    MIMETYPE,
    LAST_UPDATE,
    COLABORADOR_ID
)
SELECT
    FILENAME,
    BLOB_CONTENT,
    MIME_TYPE,
    CREATED_ON,
    :P64_COLABORADOR_ID
FROM APEX_APPLICATION_TEMP_FILES;


UPDATE CELL_EMPRESA SET 
FILENAME = (SELECT FILENAME FROM APEX_APPLICATION_TEMP_FILES),
CONTENT = (SELECT BLOB_CONTENT FROM APEX_APPLICATION_TEMP_FILES),
MIMETYPE = (SELECT MIME_TYPE FROM APEX_APPLICATION_TEMP_FILES),
LAST_UPDATE = (SELECT CREATED_ON FROM APEX_APPLICATION_TEMP_FILES)
WHERE ID_EMPRESA = :GLOBAL_FK_EMPRESA;
